services:
  vault:
    image: hashicorp/vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: pgcustodian
    ports:
      - 8200:8200
  vaultstage:
    image: hashicorp/vault
    command:
      - /host/scripts/vault_server_init.sh
    environment:
      VAULT_TOKEN: pgcustodian
      VAULT_ADDR: 'http://vault:8200'
    volumes:
      - ./:/host
  unittests:
    image: golang:bookworm
    command: |
      /host/scripts/unittests.sh
    #  sh -c "while true; do sleep 10; done"
    volumes:
      - ./:/host
    environment:
      VAULT_TOKEN: pgcustodian
      VAULT_ADDR: 'http://vault:8200'
      PGC_TOKEN_FILE: ~/.pgcustodian/token
      PGC_STORE_PATH: secret
      PGC_SECRET_PATH: pgcustodian/integration
      PGC_SECRET_KEY: key
      PGC_ENCRYPTED_FILE: /tmp/pgcustodian
  integration_tests:
    build: .
    command: |
      /host/scripts/integration_tests.sh
    #  sh -c "while true; do sleep 10; done"
    volumes:
      - ./:/host
    environment:
      VAULT_TOKEN: pgcustodian
      VAULT_ADDR: 'http://vault:8200'
      PGC_TOKEN_FILE: ~/.pgcustodian/token
      PGC_STORE_PATH: secret
      PGC_SECRET_PATH: pgcustodian/integration
      PGC_SECRET_KEY: key
      PGC_ENCRYPTED_FILE: /tmp/pgcustodian
