#!/bin/sh
set -x
APPROLE_ROLE_ID="$(cat /vaultcreds/approleid)"
export APPROLE_ROLE_ID
APPROLE_SECRET_ID_FILE=/vaultcreds/approlesecretid
export APPROLE_SECRET_ID_FILE
echo "APPROLE_SECRET_ID=$(cat "${APPROLE_SECRET_ID_FILE}")"
