#!/bin/sh
set -ex

VAULT_TOKEN=${VAULT_TOKEN-pgcustodian}
VAULT_ADDR=${VAULT_ADDR:-http://vault:8200}

PGC_ROOT_TOKEN_FILE=${PGC_ROOT_TOKEN_FILE:-~/.pgcustodian/roottoken}
PGC_ROOT_TOKEN_DIR=$(dirname "${PGC_ROOT_TOKEN_FILE}")
mkdir -p "${PGC_ROOT_TOKEN_DIR}"
echo "${VAULT_TOKEN}" >"${PGC_ROOT_TOKEN_FILE}"

PGC_ROLE_ID_FILE=${PGC_ROLE_ID_FILE:-~/.pgcustodian/role_id}
PGC_ROLE_ID_DIR=$(dirname "${PGC_ROLE_ID_FILE}")
mkdir -p "${PGC_ROLE_ID_DIR}"
curl -LH "X-Vault-Request: true" -H "X-Vault-Token: ${VAULT_TOKEN}" "${VAULT_ADDR}/v1/auth/approle/role/pgcustodian/role-id" | jq '.data.role_id' -r >"${PGC_ROLE_ID_FILE}"

PGC_SECRET_ID_FILE=${PGC_SECRET_ID_FILE:-~/.pgcustodian/secret_id}
PGC_SECRET_ID_DIR=$(dirname "${PGC_SECRET_ID_FILE}")
mkdir -p "${PGC_SECRET_ID_DIR}"
vault write -f auth/approle/role/pgcustodian/secret-id | awk '$1~/^secret_id$/{print $2}' >"${PGC_SECRET_ID_FILE}"

PGC_ROLE_ID="$(cat "${PGC_ROLE_ID_FILE}")"
export PGC_ROLE_ID PGC_SECRET_ID_FILE
